/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrabalhoAv2;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author Stefano
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpUsuario = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jlSobrenome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSobrenome = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSelecionar = new javax.swing.JButton();
        jtIdUsuario = new javax.swing.JTextField();
        jlIdUsuario = new javax.swing.JLabel();
        jpEndereco = new javax.swing.JPanel();
        jlLogradouro = new javax.swing.JLabel();
        jlComplemento = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jlCep = new javax.swing.JLabel();
        jtLogradouro = new javax.swing.JTextField();
        jtComplemento = new javax.swing.JTextField();
        jtBairro = new javax.swing.JTextField();
        jtNumero = new javax.swing.JTextField();
        jbSelecionarEndereco = new javax.swing.JButton();
        jbAlterarEndereco = new javax.swing.JButton();
        jbExcluirEndereco = new javax.swing.JButton();
        jtCep = new javax.swing.JTextField();
        jbSalvarEndereco = new javax.swing.JButton();
        jtIdEndereco = new javax.swing.JTextField();
        jlIdEndereco = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlNomePerfil = new javax.swing.JLabel();
        jtNomePerfil = new javax.swing.JTextField();
        jlDescricao = new javax.swing.JLabel();
        jtDescricao = new javax.swing.JTextField();
        jbSalvarPerfil = new javax.swing.JButton();
        jbAlterarPerfil = new javax.swing.JButton();
        jbExcluirPerfil = new javax.swing.JButton();
        jbSelecionarPerfil = new javax.swing.JButton();
        jtIdPerfil = new javax.swing.JTextField();
        jlIdPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        jlNome.setText("Nome");

        jlSobrenome.setText("Sobrenome");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSelecionar.setText("Selecionar");
        jbSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarActionPerformed(evt);
            }
        });

        jlIdUsuario.setText("ID Usuário");

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(26, 26, 26)
                        .addComponent(jtNome))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addComponent(jlSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtSobrenome))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbSelecionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jbExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addComponent(jlIdUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtIdUsuario))))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdUsuario)
                    .addComponent(jtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSobrenome)
                    .addComponent(jtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jlLogradouro.setText("Logradouro");

        jlComplemento.setText("Complemento");

        jlBairro.setText("Bairro");

        jlNumero.setText("Nº");

        jlCep.setText("CEP");

        jbSelecionarEndereco.setText("Selecionar");
        jbSelecionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarEnderecoActionPerformed(evt);
            }
        });

        jbAlterarEndereco.setText("Alterar");
        jbAlterarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarEnderecoActionPerformed(evt);
            }
        });

        jbExcluirEndereco.setText("Excluir");
        jbExcluirEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirEnderecoActionPerformed(evt);
            }
        });

        jbSalvarEndereco.setText("Salvar");
        jbSalvarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarEnderecoActionPerformed(evt);
            }
        });

        jlIdEndereco.setText("ID Endereço");

        javax.swing.GroupLayout jpEnderecoLayout = new javax.swing.GroupLayout(jpEndereco);
        jpEndereco.setLayout(jpEnderecoLayout);
        jpEnderecoLayout.setHorizontalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtComplemento))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtCep))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtBairro))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlNumero)
                                .addGap(18, 18, 18)
                                .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLogradouro)
                                    .addComponent(jlIdEndereco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtIdEndereco)
                                    .addComponent(jtLogradouro))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSelecionarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jbExcluirEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAlterarEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(108, 108, 108))
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addComponent(jbSalvarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpEnderecoLayout.setVerticalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdEndereco))
                .addGap(23, 23, 23)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlLogradouro)
                    .addComponent(jtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlComplemento)
                    .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairro)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNumero)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCep))
                .addGap(18, 18, 18)
                .addComponent(jbSalvarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluirEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecionarEndereco)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil"));

        jlNomePerfil.setText("Nome");

        jlDescricao.setText("Descrição");

        jbSalvarPerfil.setText("Salvar");
        jbSalvarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarPerfilActionPerformed(evt);
            }
        });

        jbAlterarPerfil.setText("Alterar");
        jbAlterarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPerfilActionPerformed(evt);
            }
        });

        jbExcluirPerfil.setText("Excluir");
        jbExcluirPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirPerfilActionPerformed(evt);
            }
        });

        jbSelecionarPerfil.setText("Selecionar");
        jbSelecionarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarPerfilActionPerformed(evt);
            }
        });

        jlIdPerfil.setText("ID Perfil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDescricao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSalvarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAlterarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbExcluirPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSelecionarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNomePerfil)
                            .addComponent(jlIdPerfil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtNomePerfil)
                            .addComponent(jtIdPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePerfil)
                    .addComponent(jtNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao)
                    .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbSalvarPerfil)
                .addGap(5, 5, 5)
                .addComponent(jbAlterarPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluirPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecionarPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarActionPerformed
        DaoUsuario dao = new DaoUsuario();
        List<Usuario> lista;

        lista = dao.buscarUsuario();
        for (Usuario usuario : lista) {
            jtNome.setText(usuario.getNome());
            jtSobrenome.setText(usuario.getSobrenome());
            jtIdUsuario.setText(String.valueOf(usuario.getId_usuario()));
        }


    }//GEN-LAST:event_jbSelecionarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        Usuario usuario = new Usuario();
        DaoUsuario Dao = new DaoUsuario();
        usuario.setNome(jtNome.getText());
        usuario.setSobrenome(jtSobrenome.getText());
        Dao.salvarUsuario(usuario);
        jtNome.setText("");
        jtSobrenome.setText("");
        jtIdUsuario.setText("");

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbAlterarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarEnderecoActionPerformed
        Endereco endereco = new Endereco();
        DaoEndereco dao = new DaoEndereco();
        endereco.setBairro(jtBairro.getText());
        endereco.setCep(jtCep.getText());
        endereco.setComplemento(jtComplemento.getText());
        endereco.setLogradouro(jtLogradouro.getText());
        endereco.setNumero(jtNumero.getText());
        endereco.setId_endereco(Integer.parseInt(jtIdEndereco.getText()));
        dao.alterarEndereco(endereco);
        jtNumero.setText("");
        jtLogradouro.setText("");
        jtComplemento.setText("");
        jtCep.setText("");
        jtBairro.setText("");
        jtIdEndereco.setText("");

    }//GEN-LAST:event_jbAlterarEnderecoActionPerformed

    private void jbSalvarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarEnderecoActionPerformed
        Endereco endereco = new Endereco();
        DaoEndereco Dao = new DaoEndereco();
        endereco.setBairro(jtBairro.getText());
        endereco.setCep(jtCep.getText());
        endereco.setComplemento(jtComplemento.getText());
        endereco.setLogradouro(jtLogradouro.getText());
        endereco.setNumero(jtNumero.getText());

        Dao.salvarEndereco(endereco);
        jtNumero.setText("");
        jtLogradouro.setText("");
        jtComplemento.setText("");
        jtCep.setText("");
        jtBairro.setText("");
        jtIdEndereco.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarEnderecoActionPerformed

    private void jbSalvarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarPerfilActionPerformed
        Perfil perfil = new Perfil();
        DaoPerfil Dao = new DaoPerfil();
        perfil.setNome(jtNomePerfil.getText());
        perfil.setDescricao(jtDescricao.getText());
        Dao.salvarPerfil(perfil);
        jtNomePerfil.setText("");
        jtDescricao.setText("");
        jtIdPerfil.setText("");


    }//GEN-LAST:event_jbSalvarPerfilActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        Usuario usuario = new Usuario();
        DaoUsuario dao = new DaoUsuario();
        usuario.setNome(jtNome.getText());
        usuario.setSobrenome(jtSobrenome.getText());
        usuario.setId_usuario(Integer.parseInt(jtIdUsuario.getText()));
        dao.alterarUsuario(usuario);
        jtNome.setText("");
        jtSobrenome.setText("");
        jtIdUsuario.setText("");
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Usuario usuario = new Usuario();
        DaoUsuario Dao = new DaoUsuario();
        usuario.setId_usuario(Integer.parseInt(jtIdUsuario.getText()));
        Dao.excluirUsuario(usuario.getId_usuario());
        jtNome.setText("");
        jtSobrenome.setText("");
        jtIdUsuario.setText("");
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSelecionarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarPerfilActionPerformed
        DaoPerfil dao = new DaoPerfil();
        List<Perfil> lista;

        lista = dao.buscarPerfil();
        for (Perfil perfil : lista) {
            jtNomePerfil.setText(perfil.getNome());
            jtDescricao.setText(perfil.getDescricao());

            jtIdPerfil.setText(String.valueOf(perfil.getId_perfil()));
        }


    }//GEN-LAST:event_jbSelecionarPerfilActionPerformed

    private void jbSelecionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarEnderecoActionPerformed
        DaoEndereco dao = new DaoEndereco();
        List<Endereco> lista;

        lista = dao.buscarEndereco();
        for (Endereco endereco : lista) {
            jtBairro.setText(endereco.getBairro());
            jtCep.setText(endereco.getCep());
             jtNumero.setText(endereco.getNumero());
              jtComplemento.setText(endereco.getComplemento());
              jtLogradouro.setText(endereco.getLogradouro());
            jtIdEndereco.setText(String.valueOf(endereco.getId_endereco()));
        }


    }//GEN-LAST:event_jbSelecionarEnderecoActionPerformed

    private void jbAlterarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPerfilActionPerformed
        Perfil perfil = new Perfil();
        DaoPerfil dao = new DaoPerfil();
        perfil.setNome(jtNomePerfil.getText());
        perfil.setDescricao(jtDescricao.getText());
        perfil.setId_perfil(Integer.parseInt(jtIdPerfil.getText()));
        dao.alterarPerfil(perfil);
        jtNomePerfil.setText("");
        jtDescricao.setText("");
        jtIdPerfil.setText("");


    }//GEN-LAST:event_jbAlterarPerfilActionPerformed

    private void jbExcluirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirEnderecoActionPerformed
        Endereco endereco = new Endereco();
        DaoEndereco Dao = new DaoEndereco();
        endereco.setId_endereco(Integer.parseInt(jtIdEndereco.getText()));
        Dao.excluirEndereco(endereco.getId_endereco());
        jtNumero.setText("");
        jtLogradouro.setText("");
        jtComplemento.setText("");
        jtCep.setText("");
        jtBairro.setText("");
        jtIdEndereco.setText("");
    }//GEN-LAST:event_jbExcluirEnderecoActionPerformed

    private void jbExcluirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirPerfilActionPerformed
        Perfil perfil = new Perfil();
        DaoPerfil Dao = new DaoPerfil();
        perfil.setId_perfil(Integer.parseInt(jtIdPerfil.getText()));
        Dao.excluirPerfil(perfil.getId_perfil());
        jtNomePerfil.setText("");
        jtDescricao.setText("");
        jtIdPerfil.setText("");
    }//GEN-LAST:event_jbExcluirPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAlterarEndereco;
    private javax.swing.JButton jbAlterarPerfil;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbExcluirEndereco;
    private javax.swing.JButton jbExcluirPerfil;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvarEndereco;
    private javax.swing.JButton jbSalvarPerfil;
    private javax.swing.JButton jbSelecionar;
    private javax.swing.JButton jbSelecionarEndereco;
    private javax.swing.JButton jbSelecionarPerfil;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlIdEndereco;
    private javax.swing.JLabel jlIdPerfil;
    private javax.swing.JLabel jlIdUsuario;
    private javax.swing.JLabel jlLogradouro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomePerfil;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlSobrenome;
    private javax.swing.JPanel jpEndereco;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCep;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtIdEndereco;
    private javax.swing.JTextField jtIdPerfil;
    private javax.swing.JTextField jtIdUsuario;
    private javax.swing.JTextField jtLogradouro;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNomePerfil;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtSobrenome;
    // End of variables declaration//GEN-END:variables
}
